version: 2
updates:
  -
    package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      vitest:
        applies-to: version-updates
        patterns:
          - "vitest"
          - "@vitest/browser"
          - "@vitest/browser-playwright"
        update-types:
          - major
          - minor
          - patch
      dev-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - minor
          - patch
