name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: cache npm
      uses: actions/cache@v4
      with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

    - name: cache playwright
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
    
    - name: is netlify
      uses: actions/github-script@v7
      with:
        script: |
          console.log(process.env);
          return "";
        result-encoding: string

    - name: npm ci
      run: npm ci

    - name: npm run build
      run: npm run build

    - name: npm test
      run: npm test
